# This file was generated by GoReleaser. DO NOT EDIT.
class Ship < Formula
  desc "Deploy 3rd party applications through modern pipelines"
  homepage "https://ship.replicated.com/"
  url "https://github.com/replicatedhq/ship/releases/download/v0.34.0/ship_0.34.0_darwin_amd64.tar.gz"
  version "0.34.0"
  sha256 "9e50ec70653fc954927aa7e3d3e6f9af13bb71014cad188687f484ecc6075f8f"

  def install
    bin.install "ship"
  end

  test do
    system "#{bin}/ship", "version"
  end
end
