# This file was generated by GoReleaser. DO NOT EDIT.
class Ship < Formula
  desc "Deploy 3rd party applications through modern pipelines"
  homepage "https://ship.replicated.com/"
  version "0.46.1"

  if OS.mac?
    url "https://github.com/replicatedhq/ship/releases/download/v0.46.1/ship_0.46.1_darwin_amd64.tar.gz"
    sha256 "1cb687b53d8936eaf8835b19d9873ecb1cbc8aae6b723e3f85dc496ff7426829"
  elsif OS.linux?
    url "https://github.com/replicatedhq/ship/releases/download/v0.46.1/ship_0.46.1_linux_amd64.tar.gz"
    sha256 "c13599f2c98676f11c4dda3351c0da4f1604dc9ae529226ef3be5d6a8d953339"
  end

  def install
    bin.install "ship"
  end

  test do
    system "#{bin}/ship", "version"
  end
end
